# .cargo/config.toml
# 放在專案根目錄的 .cargo/ 資料夾中

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.mips-unknown-linux-musl]
linker = "mips-linux-gnu-gcc"

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "gcc"

# 優化設定
[profile.release]
opt-level = "z"        # 優化二進位檔案大小
lto = true             # Link Time Optimization
codegen-units = 1      # 更好的優化
strip = true           # 自動 strip 除錯符號
panic = "abort"        # 減少二進位檔案大小