[build]
target-dir = "target"

[target.aarch64_cortex-a53]
linker = "aarch64-openwrt-linux-musl-gcc"
ar = "aarch64-openwrt-linux-musl-ar"
rustflags = [
  "-C", "link-arg=-static",
  "-C", "target-feature=+crt-static"
]

[env]
STAGING_DIR = { value = "./openwrt-sdk/staging_dir", relative = true }
SDK_PATH = { value = "./openwrt-sdk", relative = true }